### ISSUE TITLE
Optionally allow using `fetchEvent` to handle `wasi:http/incomingHandler@0.2.0#handle`

### ISSUE THREAD

**Issue by karthik2804** [bytecodealliance/ComponentizeJS#114]
As the title suggests, it would optionally use the `fetchEvent` that Starlingmonkey provides to handle incoming `wasi-http` requests. The upside to this would be to write apps that target a more idiomatic API which developers will be familiar with.  

https://github.com/bytecodealliance/ComponentizeJS/blob/63e3453bab9513296ad3ec65607540288487bf93/crates/spidermonkey-embedding-splicer/src/splice.rs#L56-L63

**Comment by guybedford** [comment]
Added in https://github.com/bytecodealliance/ComponentizeJS/pull/122.
