### ISSUE TITLE
Support building with `weval`

### ISSUE THREAD

**Issue by karthik2804** [bytecodealliance/ComponentizeJS#133]
I think it would be nice to optionally allow users to build components that are `weval`'d to get the performance boosts that it provides. I did manage to get a build locally working with `weval` but I am not sure on how we would like to package it in `ComponentizeJS`. 

We could include the build of StarlingMonkey for both cases with and without `weval` and also the ics-cache. This would increase the size of the package. We could optionally look at adding an optional dependency containing the build artifacts for aot if we prefer not to increase the size of the `ComponentizeJS` package. 

I am happy to open a PR once a preferred approach is identified.

**Comment by guybedford** [comment]
This would be great. It should be a relatively small PR to put together, see the example here - https://github.com/fastly/js-compute-runtime/pull/883/files.
