### ISSUE TITLE
Host Env variables are not passed through to `wizer`

### ISSUE THREAD

**Issue by karthik2804** [bytecodealliance/ComponentizeJS#135]
We currently override the envs that we provide to the `wizer` process.  [here](https://github.com/bytecodealliance/ComponentizeJS/blob/5c06448136fd8c6852b60b3a5f4c8c2f188e6734/src/componentize.js#L161-L166). This leads to `nix` like systems not being able to run `ComponentizeJS` as it needs some `NIX_LD_*` variables set. 

Is there a reason to limit the env var available to the `wizer` process or should we be okay with appending the host env vars  to the existing set.

**Comment by guybedford** [comment]
I think it would be good to make this configurable. Not exposing public environment variables by default makes sense to me for security.

So I would suggest `env: true | Record<string, string>` as a configuration option. Or maybe `'host'` instead of `true` or something similar.
