### ISSUE TITLE
Unable to disable wasi:io/poll

### ISSUE THREAD

**Issue by logaan** [bytecodealliance/ComponentizeJS#159]
When I run `jco componentize` with `--disable all` or

``` shell
      --disable clocks \
      --disable random \
      --disable http \
      --disable stdio \
      --disable stdio \
```

I still end up with a wasm file that imports `wasi:io/poll`.

jco version is 1.7.2. Running on macos.

My source file is:

``` js
wasi:io/pollexport const core = {
    foo() {
        return "bar";
    }
}
```

wit is

``` wit
package example:core;

world example {
    export core: interface {
        foo: func() -> result;
    }
}
```

and build call is

```shell
jco componentize \
    target/public/cljs-out/main-wrap.js \
    --disable clocks \
    --disable random \
    --disable http \
    --disable stdio \
    --disable stdio \
    --wit src/example/core.bare.wit \
    --world-name example \
    --out wasm/core.bare.wasm
```

I'm using `wepl` to check `.imports` and seeing poll that way.

**Comment by guybedford** [comment]
Thanks for posting, I've transferred this to ComponentizeJS - may be an issue with the latest WASI update that we don't strip all the imports. We should get this fixed for the next release.

**Comment by guybedford** [comment]
This should now be resolved by https://github.com/bytecodealliance/ComponentizeJS/pull/162.

**Comment by logaan** [comment]
Thank you! I'll test it out next time there's a release.

**Comment by kate-goldenring** [comment]
@logaan have you been able to confirm this issue is resolved for you? We are experiencing a similar issue: https://github.com/bytecodealliance/component-docs/issues/193

**Comment by kate-goldenring** [comment]
Bumping to `componentize-js` `0.16.0` and `jco` `0.9.1` resolved this for me
