### ISSUE TITLE
Option to disable stubbing `wasi:filesystem`

### ISSUE THREAD

**Issue by MendyBerger** [bytecodealliance/ComponentizeJS#170]
ComponentizeJS seems to stub all `wasi:filesystem` calls with `unreachable`. 
 https://github.com/bytecodealliance/ComponentizeJS/blob/81f5157b82af9937d1308b685cab21e364b3f11a/crates/spidermonkey-embedding-splicer/src/stub_wasi.rs#L127
 
 `wasi:io` seems to get special treatment. If imported explicitly it won't be stubbed out.
https://github.com/bytecodealliance/ComponentizeJS/blob/81f5157b82af9937d1308b685cab21e364b3f11a/crates/spidermonkey-embedding-splicer/src/stub_wasi.rs#L146-L152

This is not desired in all cases, and makes it impossible to use `wasi:filesystem` directly from within ComponentizeJS.

Would it be possible to add a check for wasi:filesystem similar to what wasi:io has?

Also, would probably be a good idea to provide an option to opt out of stubbing all together.

**Comment by karthik2804** [comment]
Hi @MendyBerger, the call to `stub_filesystem` actually does check if `wasi:fs` is imported and only then stubs it. ([ref](https://github.com/bytecodealliance/ComponentizeJS/blob/81f5157b82af9937d1308b685cab21e364b3f11a/crates/spidermonkey-embedding-splicer/src/stub_wasi.rs#L1294)). Any import defined in the world will not be stubbed.

**Comment by MendyBerger** [comment]
Thanks @karthik2804!
Don't know what I did wrong but I think it was stubbed in my local build, maybe it was different in an older version? Or I just messed up in another way...
Regardless, I ended up changing things around so that I don't really need filesystem access, so this is no longer an issue for me.
