### ISSUE TITLE
`setTimeout` support

### ISSUE THREAD

**Issue by jorge-vasquez-2301** [bytecodealliance/ComponentizeJS#56]
I'm trying to run componentize for a simple API that uses `setTimeout`:

```js
export const api = {
  "checkout": function () {
    setTimeout(() => {
      console.log("Checking out.");
    }, 1000);
  }
}
```
And I'm getting this error when running the component: `ReferenceError: setTimeout is not defined`, is there a way to solve that problem?

**Comment by willbach** [comment]
+1, I am having an issue where the `setTimeout` callback is never called. The wasm process just crashes.

**Comment by guybedford** [comment]
This is now supported with the migration to the StarlingMonkey engine.

**Comment by damianofalcioni** [comment]
Sorry to add on this issue but, despite no errors shown, the callback is never executed in my case. 
Version used: 0.11.4

**Comment by guybedford** [comment]
@damianofalcioni you must use `fetchEvent.waitUntil(promise)` to extend the incoming handler lifetime.

**Comment by damianofalcioni** [comment]
ok so this mean I have to promisify the setTimout function first right?
If this is the case, do you have a solution also for setInterval?
