### ISSUE TITLE
Is it possible to expose existing JavaScript libraries as components?

### ISSUE THREAD

**Issue by cataggar** [bytecodealliance/ComponentizeJS#59]
I'm just getting started with components. I thought it would be possible to expose existing code and libraries as components. Is this not the case?

If I add an import to the `example/hello.js`:
``` js
import process from 'node:process';

export function hello (name) {
  return `Hello ${name} ${process.version}`;
}
```

I get this error:
```
cameron@CameronsMacBook example % node componentize.js
Import 'node:process' in source.js is not defined as a world import. Only component-defined imports can be used.
Unable to link the source code. Imports should be:
```

I read through https://component-model.bytecodealliance.org/ .

**Comment by guybedford** [comment]
We currently don't support Node.js compatibility layers out of the box, so you would need to setup a custom build step and polyfill approach to substitute these imports manually.

Agreed we should get there eventually.

**Comment by cataggar** [comment]
Is there an example polyfill approach that I could use for guidance?

**Comment by guybedford** [comment]
Moving to https://github.com/fermyon/StarlingMonkey/issues/15.

**Comment by cataggar** [comment]
It was moved to
https://github.com/bytecodealliance/StarlingMonkey/issues/15
