### ISSUE TITLE
Update to latest wasi RC's v0.2.0-rc-2023-12-05

### ISSUE THREAD

**Issue by ricochet** [bytecodealliance/ComponentizeJS#75]
Wastime 16 now supports rc-2023-12-05 for wasi-http and wasi-cli.

https://github.com/WebAssembly/wasi-http/releases/tag/v0.2.0-rc-2023-12-05

**Comment by guybedford** [comment]
Thanks for the ping, I'm getting the release cycle together now for JCO and ComponentizeJS - should be up later today / early tomorrow.

**Comment by guybedford** [comment]
Released in 0.6.0.
