### ISSUE TITLE
Import packages from npm

### ISSUE THREAD

**Issue by stevesloka** [bytecodealliance/ComponentizeJS#77]
I am looking to build on the provided examples and support the ability to add `npm` packages that my users might want to import. 

I tried to just add an `import` to my `hello.js`, but when I try and build the wasm module I get the following error. Is there a way to import that I'm overlooking?

```bash
$ node componentize.mjs                                                          
Import 'randomstring' in source.js is not defined as a world import. Only component-defined imports can be used.
Unable to link the source code. Imports should be:


```

Code: 
```js
import randomstring from "randomstring";

export function hello(name) {
  return `Hello ${name} - ${randomstring.generate(10)}`;
}

```

**Comment by stevesloka** [comment]
I tried to use `esbuild` to bundle things up, but couldn't get it working. I did find an example with `rollupjs` which did work (or at least the example was enough to properly compile things together). 

So the TLDR is that you can use external packages, as long as they are embedded in the file you are compiling against.

**Comment by guybedford** [comment]
Yes, custom bundling is required for now. We may introduce bundling by default / builtins support / better workflows here in future but for now it is entirely custom.

**Comment by stevesloka** [comment]
@guybedford circling back here a bit. I've been toying around with ComponentizeJS and Javy. When I got npm packages working, it was on Javy, but I'm curious how I'd also implement this with ComponentizeJS.

Do you have any tips on where I'd bundle code? When I use esbuild to bundle things up, I get an error: 

```
source.js:197:1 ReferenceError: module is not defined
```

**Comment by lwansbrough** [comment]
Hey @guybedford, are you aware of any examples which support such bundling?

**Comment by guybedford** [comment]
@lwansbrough you can use a tool like esbuild or RollupJS to do this, outputting for the "esm" output format to run in ComponentizeJS.

**Comment by LostInBrittany** [comment]
I have done several examples with RollupJS, they are mostly trivial, but if you think they can help, I can put them in a repository and put the link here

**Comment by lwansbrough** [comment]
Thank you both, I think with that nudge I can figure it out. Appreciate your time.

**Comment by LostInBrittany** [comment]
Here you have a very simple example using RollupJS: https://github.com/LostInBrittany/example-componentizeJS-with-external-deps

**Comment by hugomrdias** [comment]
Check out our "wasmify" module https://github.com/fission-codes/stack/blob/main/packages/homestar/src/wasmify/index.js does types transform to wit, bundling, wasi imports support and more.

**Comment by guybedford** [comment]
Moving to https://github.com/fermyon/StarlingMonkey/issues/15.

**Comment by joebowbeer** [comment]
@guybedford https://github.com/bytecodealliance/StarlingMonkey/issues/15 ?

fermyon forked from BCA has no public issues
