### ISSUE TITLE
Avoid process.exit 

### ISSUE THREAD

**Issue by hugomrdias** [bytecodealliance/ComponentizeJS#90]
Would you be open to remove process.exit for a throw ? 

I'm using componentizejs to build a CLI that wraps bundling, auto wit world creation, wasi imports etc but i need to control the exits on my side. 

https://github.com/fission-codes/stack/blob/main/packages/homestar/src/wasmify/index.js

I would do a PR, just asking if you would be open to it 

Thanks.

**Comment by guybedford** [comment]
This actually happens on the Jco side when you execute I think?

So it's probably [this exit](https://github.com/bytecodealliance/jco/blob/main/packages/preview2-shim/lib/nodejs/cli.js#L48) you are seeing at runtime, in which case you may even be able to import and monkey patch that interface.

**Comment by hugomrdias** [comment]
I'm not using jco, it's this one
https://github.com/bytecodealliance/ComponentizeJS/blob/main/src/componentize.js#L313

Hugo Dias

**Comment by guybedford** [comment]
Ahh, yes sure we can remove that!

**Comment by guybedford** [comment]
This was removed in https://github.com/bytecodealliance/ComponentizeJS/commit/ebeb262b788f7285a404b9fde4f95340c4d1789f.
