### ISSUE TITLE
Documentation disagrees with itself

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/ComponentizeJS#97]
In the [Usage](https://github.com/bytecodealliance/ComponentizeJS?tab=readme-ov-file#usage) section, `componentize` is a 3-argument function.

In the [API](https://github.com/bytecodealliance/ComponentizeJS?tab=readme-ov-file#api) section, `componentize` is a 2-argument function.

In the [example](https://github.com/bytecodealliance/ComponentizeJS/blob/main/EXAMPLE.md), `componentize` is a 2-argument function but the types are different from the previous case.

Also it looks like `enableStdout` might no longer exist?

**Comment by guybedford** [comment]
All three are correct believe it or not, thanks to the magic of JavaScript. Signatures are:

```ts
function componentize(source: string, opts: ComponentizeOptions)
function componentize(source: string, witWorld: string, opts: ComponentizeOptions)
function componentize(source: string, witWorld: string)
```

We should certainly add a TypeScript type at some point if it would be useful.

Yes `enableStdout` was replaced with `disableFeatures: ['stdio']` is it still referenced somewhere?

**Comment by whitequark** [comment]
> All three are correct believe it or not, thanks to the magic of JavaScript. 

I think the complete signature or signatures should be referenced at least somewhere.

> We should certainly add a TypeScript type at some point if it would be useful.

Yeah, I use TypeScript.

> Yes `enableStdout` was replaced with `disableFeatures: ['stdio']` is it still referenced somewhere?

In the Usage section, yes.

**Comment by guybedford** [comment]
Thanks for calling this out, added an update in https://github.com/bytecodealliance/ComponentizeJS/pull/98.
